name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.4.10
          - 2.5.9
          - 2.6.10
          - 2.7.7
        appraisal:
          - rails_4_2
          - rails_5_0
          - rails_5_1
          - rails_5_2
          - rails_6_0
        test_framework:
          - minitest
          - test_unit
        exclude:
          - { ruby: 2.4.10, appraisal: rails_6_0 }
          - { ruby: 2.4.10, appraisal: rails_5_2 }
          - { ruby: 2.4.10, appraisal: rails_5_1 }
          - { ruby: 2.6.10, appraisal: rails_4_2 }
          - { ruby: 2.7.7, appraisal: rails_4_2 }
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.appraisal }}.gemfile
      TEST_FRAMEWORK: ${{ matrix.test_framework }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        id: set-up-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: v1-rubygems-local-${{ runner.os }}-${{ matrix.ruby }}-${{ hashFiles(format('gemfiles/{0}.gemfile.lock', matrix.appraisal)) }}
      - name: Install dependencies
        run: bundle install --jobs=3 --retry=3
      - name: Run Tests
        run: bundle exec rake
